name: Injetar e Salvar no Repo
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [tina-cloud-publish]

jobs:
  process-html:
    runs-on: ubuntu-latest
    # Evita loop infinito se o robô fizer o commit
    if: github.event.head_commit.author.name != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Rodar Script
        run: node post-build-inject.cjs

      - name: Salvar Mudanças no GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: injeção de dados" && git push)